import type { EpisodeContext } from '@/cli/episode.js';
import type { Node } from '@/graph/build.js';
import type { ArtifactRecord } from '@/ledger/schema.js';
import type { NodeStatus } from '@/state/resolve.js';
import type { Identity } from '@/manifest/schema.js';

/**
 * `pc readme` (the generator). Produces the per-episode README from the SAME facts every other
 * verb answers from — the manifest, the graph, and the committed ledger — so it never drifts from
 * reality and never states provenance a human has to remember to update.
 *
 * The document's job is to make provenance unmistakable: which objects a human authored, which a
 * machine generated (and must not be mistaken for authored work), and which are reproducible build
 * outputs that are not committed at all. Every claim here is derived, not narrated — so this file
 * is regenerated, never hand-edited.
 *
 * It is deliberately NOT a description of what each role "means" (that would be the generator
 * inventing subject knowledge it does not have). It states what is verifiable: kind, path,
 * provenance, lineage, and current state.
 */
export function generateReadme(ctx: EpisodeContext): string {
  const stateById = new Map<Identity, NodeStatus>(ctx.status.nodes.map((n) => [n.id, n]));
  const recordById = ctx.ledger.artifacts;

  // A derived node is AI-generated (non-reproducible, committed under ai-generated/) exactly when it
  // is impure — and impurity can be declared by the profile (decl) OR by the provider at build time
  // (recorded as producer_impure). This mirrors the routing in providers/build.ts (`impurityOf`), so
  // the README can never disagree with where a build actually put its bytes.
  const isImpure = (n: Node): boolean =>
    recordById[n.id]?.producer_impure !== undefined || n.provider?.impure !== undefined;

  const nodes = [...ctx.graph.nodes.values()];
  const authored = nodes.filter((n) => n.kind === 'authored');
  const aiGenerated = nodes.filter((n) => n.kind === 'derived' && isImpure(n));
  const reproducible = nodes.filter((n) => n.kind === 'derived' && !isImpure(n));

  const lines: string[] = [];
  lines.push(`# ${ctx.manifest.title}`);
  lines.push('');
  lines.push(
    '<!-- Generated by production-control (`pc readme`). Every object is listed with its',
    '     provenance, derived from episode.yaml and the committed ledger. Do NOT hand-edit —',
    '     run `pc readme` to refresh. -->'
  );
  lines.push('');
  lines.push(`**Episode:** \`${ctx.manifest.id}\`  ·  **Profile:** \`${ctx.manifest.profile}\``);
  lines.push('');

  lines.push('## Authored inputs');
  lines.push('');
  lines.push(
    'Declared inputs with no recorded producer. production-control does not generate or alter',
    'these, and it makes NO claim about how they were created — a human, an AI, some other tool:',
    'their provenance is outside what production-control tracks. Whoever supplies them owns that.'
  );
  lines.push('');
  for (const node of authored) {
    lines.push(...authoredEntry(node, stateById.get(node.id)));
  }
  if (authored.length === 0) {
    lines.push('_None declared._', '');
  }

  lines.push('## AI-generated — produced here by an impure tool');
  lines.push('');
  lines.push(
    'production-control produced these by running an impure tool, so it KNOWS they are',
    'machine-derived and not reproducible — the exact bytes are COMMITTED (under `ai-generated/`)',
    'as the durable record. Do not mistake them for authored content: the authored inputs above',
    'are written from them (an authored input that `follows` one is written against it).'
  );
  lines.push('');
  for (const node of aiGenerated) {
    lines.push(...derivedEntry(node, stateById.get(node.id), recordById[node.id], true));
  }
  if (aiGenerated.length === 0) {
    lines.push('_None._', '');
  }

  lines.push('## Reproducible build outputs — gitignored');
  lines.push('');
  lines.push(
    'Derived by a pure tool from authored inputs and regenerable with `pc build`; not committed',
    '(they live under `dist/`).'
  );
  lines.push('');
  for (const node of reproducible) {
    lines.push(...derivedEntry(node, stateById.get(node.id), recordById[node.id], false));
  }
  if (reproducible.length === 0) {
    lines.push('_None._', '');
  }

  return lines.join('\n') + '\n';
}

function authoredEntry(node: Node, status: NodeStatus | undefined): string[] {
  const out = [`### ${node.id}`, `- **Path:** \`${node.path ?? '(none)'}\``];
  out.push(
    '- **Provenance:** authored input — production-control records no producer and does not track how it was created.'
  );
  if (node.follows !== undefined) {
    out.push(
      `- **Follows (advisory):** \`${node.follows}\` — resolved by a recorded review, never rebuilt.`
    );
  }
  out.push(`- **State:** ${stateLine(status)}`);
  out.push('');
  return out;
}

function derivedEntry(
  node: Node,
  status: NodeStatus | undefined,
  record: ArtifactRecord | undefined,
  aiGenerated: boolean
): string[] {
  const from = (node.inputs ?? []).map((i) => `\`${i}\``).join(', ') || '(no inputs)';
  const out = [`### ${node.id}`];
  const kind = aiGenerated
    ? 'AI-generated (machine-derived, not human-crafted)'
    : 'reproducible build output';
  if (record !== undefined) {
    out.push(`- **Path:** \`${record.output.path}\``);
    out.push(
      `- **Provenance:** ${kind}. Produced by \`${record.producer.tool} ${record.producer.version}\` from ${from}.`
    );
    if (record.producer_impure !== undefined) {
      out.push(`- **Impure:** ${record.producer_impure.reason}`);
    }
    out.push(
      `- **Built:** ${record.built_at} · output \`${shortHash(record.output.hash)}\`` +
        inputHashes(record.inputs)
    );
  } else {
    out.push(`- **Provenance:** ${kind}, from ${from}. Not yet built.`);
    if (node.provider?.impure !== undefined) {
      out.push(`- **Impure (declared):** ${node.provider.impure.reason}`);
    }
  }
  out.push(`- **State:** ${stateLine(status)}`);
  out.push('');
  return out;
}

function inputHashes(inputs: Readonly<Record<Identity, string>>): string {
  const entries = Object.entries(inputs);
  if (entries.length === 0) {
    return '';
  }
  return ' · inputs: ' + entries.map(([id, hash]) => `${id} \`${shortHash(hash)}\``).join(', ');
}

/** A short, human-readable hash. The committed ledger holds the full hash and is authoritative. */
function shortHash(hash: string): string {
  const [algo, digest] = hash.split(':');
  return digest === undefined ? hash : `${algo}:${digest.slice(0, 12)}…`;
}

function stateLine(status: NodeStatus | undefined): string {
  if (status === undefined) {
    return '(unknown)';
  }
  return `\`${status.state}\` — ${status.cause.message}`;
}
